Feature/paged response sublists
entando/web-commons pull request #4
Opened 2019-09-02 22:26 UTC by ffleandro

Added auxiliary constructors for trimming paged lists.

Merges branch feature-entando-arch that brings some functionalities from entando-core for filtering and paginating responses.

2019-09-02 22:26 UTC, entando-service commented
Something went wrong. Investigate!

2019-09-20 14:32 UTC, entando-service commented
Something went wrong. Investigate!

2019-09-20 17:48 UTC, entando-service commented
Something went wrong. Investigate!

2019-09-20 19:43 UTC, entando-service commented
Something went wrong. Investigate!

2019-09-20 20:13 UTC, entando-service commented
Something went wrong. Investigate!

2019-09-26 17:52 UTC, entando-service commented
Something went wrong. Investigate!

2019-09-26 18:00 UTC, entando-service commented
All is well

2019-09-26 20:05 UTC, entando-service commented
All is well

2019-09-27 01:56 UTC, werbth requested changes

2019-09-27 01:56 UTC, werbth commented on src/main/java/org/entando/web/controller/ControllerExceptionHandler.java
> +		return ResponseEntity.status(400).body(new ErrorResponse(message));
Use the constant HttpStatus.BAD_REQUEST for status method.

2019-09-27 11:50 UTC, entando-service commented
All is well

2019-09-27 13:42 UTC, entando-service commented
All is well

2019-09-27 14:04 UTC, werbth approved these changes

2019-09-27 17:54 UTC, merged